### PR TITLE
feat: add support for decontaining open tab

### LINKED ISSUE #17: Decontain shortcut
Hi, I really like this extension! Much better than manually switching with button clicks using other extensions. However one feature I miss is the ability to switch a tab to the "default container", or "decontain" it. A shortcut that might make sense for this would be ctrl+alt+0. Thoughts?

### PR DESCRIPTION
**Pull request by zanona**
resolves #17

### CODE REVIEW

**Comment by gsomoza** [comment]
Thanks for doing this! What you last mentioned is a small but good optimization, let's do it!

**Comment by gsomoza** [comment]
Ended up applying this quick fix myself and merged - will release later today! Thanks again!

**Comment by gsomoza** [comment]
FYI released just now

**Comment by zanona** [comment]
> FYI released just now

Thanks a lot! :D

**Pull request merged**
